config/routes.rb
Rails.application.routes.draw do
  resources :companies

  resources :weight_entries

  resources :competitions do
  member do
    get "vote"
  end
end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/weight_entry.rb
class WeightEntry < ActiveRecord::Base
  belongs_to :user
  belongs_to :competition
end

app/controllers/weight_entries_controller.rb
class WeightEntriesController < ApplicationController
  before_action :set_weight_entry, only: [:show, :edit, :update, :destroy]

  # GET /weight_entries
  # GET /weight_entries.json
  def index
    @weight_entries = WeightEntry.all
  end

  # GET /weight_entries/1
  # GET /weight_entries/1.json
  def show
  end

  # GET /weight_entries/new
  def new
    @weight_entry = WeightEntry.new
  end

  # GET /weight_entries/1/edit
  def edit
  end

  # POST /weight_entries
  # POST /weight_entries.json
  def create
    @weight_entry = WeightEntry.new(weight_entry_params)

    respond_to do |format|
      if @weight_entry.save
        format.html { redirect_to @weight_entry, notice: 'Weight entry was successfully created.' }
        format.json { render :show, status: :created, location: @weight_entry }
      else
        format.html { render :new }
        format.json { render json: @weight_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weight_entries/1
  # PATCH/PUT /weight_entries/1.json
  def update
    respond_to do |format|
      if @weight_entry.update(weight_entry_params)
        format.html { redirect_to @weight_entry, notice: 'Weight entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @weight_entry }
      else
        format.html { render :edit }
        format.json { render json: @weight_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weight_entries/1
  # DELETE /weight_entries/1.json
  def destroy
    @weight_entry.destroy
    respond_to do |format|
      format.html { redirect_to weight_entries_url, notice: 'Weight entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weight_entry
      @weight_entry = WeightEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weight_entry_params
      params.require(:weight_entry).permit(:weight, :user_id, :competition_id)
    end
end

app/helpers/weight_entries_helper.rb
module WeightEntriesHelper
end

app/views/weight_entries/_form.html.erb
<%= form_for @weight_entry, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :weight, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :weight, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  weight_entries_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/weight_entries/edit.html.erb
<%- model_class = WeightEntry -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => WeightEntry %></h1>
</div>
<%= render :partial => 'form' %>

app/views/weight_entries/index.html.erb
<%- model_class = WeightEntry -%>
<div class="page-header">
  <h1><%=t '.title', :default => WeightEntry %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:weight) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @weight_entries.each do |weight_entry| %>
      <tr>
        <td><%= weight_entry.id %></td>
        <td><%= weight_entry.weight %></td>
        <td><%=l weight_entry.created_at, format: :long %></td>
        <td>
          <%= link_to weight_entry_path(weight_entry), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to weight_entry_path(weight_entry), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_weight_entry_path,
            :class => 'btn btn-primary' %>

app/views/weight_entries/new.html.erb
<%- model_class = WeightEntry -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => WeightEntry %></h1>
</div>
<%= render :partial => 'form' %>

app/views/weight_entries/show.html.erb
<%- model_class = WeightEntry -%>
<div class="page-header">
  <h1><%=t '.title', :default => WeightEntry %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:weight) %></dt>
      <dd><pre class="prettyprint"><%= @weight_entry.weight %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              weight_entries_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_weight_entry_path(@weight_entry), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              weight_entry_path(@weight_entry),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>